source ./parse.sh

echo $GCLOUD_ACCESS_TOKEN

docker build -t sso-app .

docker run -p 5000:5000 \
  -e GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
  -e GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
  -e FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
  -e GCLOUD_ACCESS_TOKEN="$GCLOUD_ACCESS_TOKEN" \
  sso-app